apiVersion: v1
kind: Pod
metadata:
  name: bad-sleep
  labels:
    app:  bad
spec:
  containers:
    - name: bad-sleep
      image: courselabs/bad-sleep

---

apiVersion: v1
kind: Service
metadata:
  name: bad-sleep-service
  labels:
    name: bad-sleep-service
spec:
  selector:
    app: bad
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP      

  