apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app:  result-app
    name: result-pod
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80